"""
Task Scheduler for AI Employee Vault
Manages scheduled tasks like daily briefings, weekly audits, etc.
Uses APScheduler for cross-platform scheduling
"""

import logging
from pathlib import Path
from datetime import datetime, time
import json

try:
    from apscheduler.schedulers.background import BackgroundScheduler
    from apscheduler.triggers.cron import CronTrigger
    SCHEDULER_AVAILABLE = True
except ImportError:
    SCHEDULER_AVAILABLE = False
    logging.warning("APScheduler not installed. Install with: pip install apscheduler")


class TaskScheduler:
    """Manages scheduled tasks for AI Employee"""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.logs = self.vault_path / 'Logs'
        self.briefings = self.vault_path / 'Briefings'
        self.business_updates = self.vault_path / 'Business_Updates'

        # Create directories
        self.logs.mkdir(exist_ok=True)
        self.briefings.mkdir(exist_ok=True)
        self.business_updates.mkdir(exist_ok=True)

        # Set up logging
        self.logger = logging.getLogger(__name__)
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )

        # Initialize scheduler
        self.scheduler = None
        if SCHEDULER_AVAILABLE:
            self.scheduler = BackgroundScheduler()

    def generate_daily_briefing(self):
        """Generate daily briefing at 8:00 AM"""
        self.logger.info("Generating daily briefing...")

        briefing_content = f"""---
generated: {datetime.now().isoformat()}
type: daily_briefing
period: {datetime.now().strftime('%Y-%m-%d')}
---

# Daily Briefing - {datetime.now().strftime('%A, %B %d, %Y')}

## Executive Summary
Good morning! Here's your daily briefing.

## Pending Tasks
- Review items in /Needs_Action folder
- Check /Pending_Approval for items requiring your attention
- Review completed tasks in /Done folder

## Today's Schedule
- 9:00 AM: Review emails and messages
- 12:00 PM: Lunch break
- 2:00 PM: Business development
- 4:00 PM: Review and planning

## Key Metrics
- Pending tasks: [Auto-calculated]
- Completed today: [Auto-calculated]
- Approval requests: [Auto-calculated]

## Recommendations
1. Process high-priority items first
2. Review approval requests
3. Update business goals if needed

---
*Generated by AI Employee Scheduler*
*{datetime.now().isoformat()}*
"""

        try:
            briefing_file = self.briefings / f"{datetime.now().strftime('%Y-%m-%d')}_briefing.md"
            briefing_file.write_text(briefing_content, encoding='utf-8')
            self.logger.info(f"Daily briefing created: {briefing_file}")
            self.log_scheduled_action('daily_briefing', 'success')
        except Exception as e:
            self.logger.error(f"Error generating daily briefing: {e}")
            self.log_scheduled_action('daily_briefing', 'failed')

    def generate_weekly_audit(self):
        """Generate weekly business audit on Sunday at 8:00 PM"""
        self.logger.info("Generating weekly business audit...")

        audit_content = f"""---
generated: {datetime.now().isoformat()}
type: weekly_audit
period: {datetime.now().strftime('%Y-W%W')}
---

# Weekly Business Audit - Week {datetime.now().strftime('%W, %Y')}

## Executive Summary
Weekly audit and business review.

## Revenue Summary
- This week: $[Auto-calculated]
- Month to date: $[Auto-calculated]
- Target: $[From Business_Goals.md]

## Completed Tasks
- [Auto-populated from /Done folder]

## Pending Items
- [Auto-populated from /Needs_Action folder]

## Bottlenecks Identified
- [Analysis of delayed tasks]

## Cost Analysis
- Subscriptions: $[Auto-calculated]
- Unused services: [Flagged for review]
- Optimization opportunities: [Identified]

## Proactive Suggestions
1. [AI-generated recommendations]
2. [Cost optimization opportunities]
3. [Process improvements]

## Next Week's Focus
- [Priority items for next week]

---
*Generated by AI Employee Scheduler*
*{datetime.now().isoformat()}*
"""

        try:
            audit_file = self.briefings / f"{datetime.now().strftime('%Y-%m-%d')}_weekly_audit.md"
            audit_file.write_text(audit_content, encoding='utf-8')
            self.logger.info(f"Weekly audit created: {audit_file}")
            self.log_scheduled_action('weekly_audit', 'success')
        except Exception as e:
            self.logger.error(f"Error generating weekly audit: {e}")
            self.log_scheduled_action('weekly_audit', 'failed')

    def process_scheduled_posts(self):
        """Process scheduled LinkedIn posts"""
        self.logger.info("Processing scheduled LinkedIn posts...")

        try:
            scheduled_folder = self.business_updates / 'scheduled'
            if scheduled_folder.exists():
                for post_file in scheduled_folder.glob('*.md'):
                    self.logger.info(f"Processing scheduled post: {post_file.name}")
                    # Move to pending approval
                    approval_file = self.vault_path / 'Pending_Approval' / f"LINKEDIN_POST_{post_file.name}"
                    post_file.rename(approval_file)

            self.log_scheduled_action('process_posts', 'success')
        except Exception as e:
            self.logger.error(f"Error processing scheduled posts: {e}")
            self.log_scheduled_action('process_posts', 'failed')

    def cleanup_old_logs(self):
        """Clean up logs older than 90 days"""
        self.logger.info("Cleaning up old logs...")

        try:
            from datetime import timedelta
            cutoff_date = datetime.now() - timedelta(days=90)

            for log_file in self.logs.glob('*.json'):
                try:
                    file_date = datetime.fromisoformat(log_file.stem)
                    if file_date < cutoff_date:
                        log_file.unlink()
                        self.logger.info(f"Deleted old log: {log_file.name}")
                except Exception as e:
                    self.logger.debug(f"Error processing log file: {e}")

            self.log_scheduled_action('cleanup_logs', 'success')
        except Exception as e:
            self.logger.error(f"Error cleaning up logs: {e}")
            self.log_scheduled_action('cleanup_logs', 'failed')

    def log_scheduled_action(self, action: str, status: str):
        """Log scheduled action to audit trail"""
        log_file = self.logs / f"{datetime.now().strftime('%Y-%m-%d')}.json"

        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'action': action,
            'status': status,
            'component': 'scheduler'
        }

        try:
            if log_file.exists():
                logs = json.loads(log_file.read_text())
            else:
                logs = []

            logs.append(log_entry)
            log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')
        except Exception as e:
            self.logger.error(f"Error logging action: {e}")

    def start_scheduler(self):
        """Start the background scheduler"""
        if not SCHEDULER_AVAILABLE:
            self.logger.error("APScheduler not available. Install with: pip install apscheduler")
            return False

        try:
            # Daily briefing at 8:00 AM
            self.scheduler.add_job(
                self.generate_daily_briefing,
                CronTrigger(hour=8, minute=0),
                id='daily_briefing',
                name='Daily Briefing at 8:00 AM'
            )

            # Weekly audit on Sunday at 8:00 PM
            self.scheduler.add_job(
                self.generate_weekly_audit,
                CronTrigger(day_of_week=6, hour=20, minute=0),
                id='weekly_audit',
                name='Weekly Audit on Sunday at 8:00 PM'
            )

            # Process scheduled posts daily at 9:00 AM
            self.scheduler.add_job(
                self.process_scheduled_posts,
                CronTrigger(hour=9, minute=0),
                id='process_posts',
                name='Process Scheduled Posts at 9:00 AM'
            )

            # Cleanup old logs monthly on the 1st at 2:00 AM
            self.scheduler.add_job(
                self.cleanup_old_logs,
                CronTrigger(day=1, hour=2, minute=0),
                id='cleanup_logs',
                name='Cleanup Old Logs on 1st at 2:00 AM'
            )

            self.scheduler.start()
            self.logger.info("Scheduler started successfully")
            self.logger.info("Scheduled jobs:")
            for job in self.scheduler.get_jobs():
                self.logger.info(f"  - {job.name}: {job.trigger}")

            return True

        except Exception as e:
            self.logger.error(f"Error starting scheduler: {e}")
            return False

    def stop_scheduler(self):
        """Stop the background scheduler"""
        if self.scheduler and self.scheduler.running:
            self.scheduler.shutdown()
            self.logger.info("Scheduler stopped")

    def get_scheduled_jobs(self) -> list:
        """Get list of scheduled jobs"""
        if not self.scheduler:
            return []

        jobs = []
        for job in self.scheduler.get_jobs():
            jobs.append({
                'id': job.id,
                'name': job.name,
                'trigger': str(job.trigger),
                'next_run': job.next_run_time.isoformat() if job.next_run_time else None
            })

        return jobs

    def demo_run(self):
        """Demo run that shows scheduler capabilities"""
        self.logger.info("Running Task Scheduler in demo mode")

        # Generate sample briefing
        self.generate_daily_briefing()

        # Generate sample audit
        self.generate_weekly_audit()

        self.logger.info("Demo run complete")


if __name__ == "__main__":
    # Initialize the scheduler
    VAULT_PATH = Path(".")

    scheduler = TaskScheduler(vault_path=VAULT_PATH)

    # For demo purposes, generate sample briefings
    scheduler.demo_run()

    print(f"\nTask Scheduler setup complete!")
    print(f"Briefings created in: {scheduler.briefings}")

    if SCHEDULER_AVAILABLE:
        print(f"\nTo start the scheduler:")
        print(f"  scheduler.start_scheduler()")
        print(f"\nTo view scheduled jobs:")
        print(f"  scheduler.get_scheduled_jobs()")
    else:
        print(f"\nAPScheduler not installed. Install with:")
        print(f"  pip install apscheduler")
